<?php

use Carbon\Carbon;
use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class TasksControllerTest extends TestCase
{
    use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->migrateDatabases();
        $this->usingInMemoryDatabases();
        $this->seed();
    }

    /**
     * Get A List of Tasks
     */
    public function test_get_a_list_tasks(): void
    {
        $response = $this->get('/api/tasks');

        $response->assertJsonCount(10, 'data');
        $response->assertJsonStructure([
            'current_page',
            'data' => [
                '*' => [
                    'id',
                    'title',
                    'description',
                    'status',
                    'due_date',
                    'created_at',
                    'updated_at',
                ]
            ],
            'first_page_url',
            'from',
            'last_page',
            'last_page_url',
            'links' => [
                '*' => [
                    'url',
                    'label',
                    'page',
                    'active'
                ]
            ],
            'next_page_url',
            'path',
            'per_page',
            'prev_page_url',
            'to',
            'total'
        ]);

        $response->assertStatus(200);
    }

    /**
     * Create a Task
     */
    public function test_create_a_tasks(): void
    {
        $response = $this->post('/api/tasks', [
            'title' => 'Create South Yorkshire Mayoral Combined Authority',
            'description' => 'The South Yorkshire Mayoral Combined Authority is the combined authority for South Yorkshire in England, with powers over transport, economic development and regeneration. It covers a total area of 3,484 km² with a population of 1.4 million.',
            'status' => 'in_progress',
            'due_date' => Carbon::today()->addDays(2)->toDateString(),
        ]);

        $response->assertStatus(201);
    }

    /**
     * Update status of a task
     */
    public function test_update_a_tasks(): void
    {
        $response = $this->put('/api/tasks/2', [
            'status' => 'in_progress',
        ]);

        $response->assertJsonFragment(['status' => 'in_progress']);

        $response->assertStatus(200);
    }

    /**
     * Delete a Task
     */
    public function test_delete_a_tasks(): void
    {
        $response = $this->delete('/api/tasks/10');

        $response->assertStatus(204);
    }
}
